version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    S3_BUCKET: "magesh-portfolio"
    BUILD_DIR: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React/Vite app..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3 bucket: $S3_BUCKET..."
      - aws s3 sync $BUILD_DIR/ s3://$S3_BUCKET/ --delete
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - '**/*'
