name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t magesh-portfolio .
          docker tag magesh-portfolio:latest 983050536265.dkr.ecr.ap-south-1.amazonaws.com/magesh-portfolio:latest

      # 5. Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push 983050536265.dkr.ecr.ap-south-1.amazonaws.com/magesh-portfolio:latest

      # 6. Update ECS service
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json   # path to your ECS task definition JSON
          service: magesh-portfolio
          cluster: magesh-portfolio-2
          wait-for-service-stability: true
